services:
  - type: web
    name: poultry-farm-ai-ml
    runtime: python
    plan: free
    buildCommand: pip install --no-cache-dir -r requirements_server.txt
    startCommand: uvicorn cloud_ml_server:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: FIREBASE_URL
        value: https://poultry-database-2b2d1-default-rtdb.firebaseio.com
